# Generated by Django 3.2 on 2023-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_alter_userprofile_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deposite',
            field=models.CharField(blank=True, default='5', max_length=10, null=True, verbose_name='deposite'),
        ),
    ]
