# Generated by Django 3.2 on 2023-01-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_alter_userprofile_deposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Buyer'), ('2', 'Seller')], default='1', max_length=10, null=True, verbose_name='user_type'),
        ),
    ]
