# Generated by Django 3.2 on 2023-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20230119_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='amountp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deposite',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='deposite'),
        ),
    ]
