# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-15 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='products_productsmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('video', models.FileField(blank=True, null=True, upload_to='Videos/%Y/%m/', verbose_name='video')),
                ('external_link_name', models.CharField(blank=True, max_length=255, verbose_name='Link Name')),
                ('external_link', models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, validators=[products.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link')),
                ('target', models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Link Target')),
                ('sorting', models.BigIntegerField(default=0, null=True, verbose_name='sorting')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='category')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-sorting', '-id'),
            },
            bases=('cms.cmsplugin',),
        ),
    ]
