# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-15 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='video',
        ),
    ]
