# Generated by Django 3.2 on 2023-01-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('products', '0002_remove_productsmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='If provided, overrides the external link.', limit_choices_to={'publisher_is_draft': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='category'),
        ),
    ]
