# Generated by Django 3.2 on 2023-01-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_productsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='amount',
            field=models.CharField(default='1', max_length=10, null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
