# Generated by Django 3.2 on 2023-01-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20230115_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
    ]
