# Generated by Django 3.2 on 2023-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230115_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, null=True, verbose_name='cost'),
        ),
    ]
