# Generated by Django 3.2 on 2023-01-19 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20230115_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='products_transactionmodel', serialize=False, to='cms.cmsplugin')),
                ('amount', models.CharField(default='1', max_length=10, null=True, verbose_name='amount')),
                ('sorting', models.BigIntegerField(default=0, null=True, verbose_name='sorting')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='buyer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ProductBuyer',
                'verbose_name_plural': 'ProductsBuyers',
                'ordering': ('-sorting', '-id'),
            },
            bases=('cms.cmsplugin',),
        ),
    ]
