# Generated by Django 3.2 on 2023-01-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230119_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='amount_num',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='amount'),
        ),
    ]
