# Generated by Django 3.2 on 2023-01-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230119_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='sorting',
        ),
    ]
